name=I2C_ABP2
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for the Honeywell I2C ABP2 pressure sensors.
paragraph=
category=Sensors
url=https://github.com/RobTillaart/I2C_ABP2
architectures=*
includes=I2C_ABP2.h
depends=
