name=M61538FP
version=0.1.2
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for M61538FP 6 channel audio volume processor.
paragraph=
category=Other
url=https://github.com/RobTillaart/M61538FP
architectures=*
includes=M61538FP.h
depends=
