name=lengthConverter
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for to convert units of length.
paragraph=
category=Sensors
url=https://github.com/RobTillaart/lengthConverter
architectures=*
includes=lengthConverter.h
depends=
