name=AD5684
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for AD5684/5/6 4 channel SPI-DAC (12/14/16 bit).
paragraph=DAC, SPI.
category=Signal Input/Output
url=https://github.com/RobTillaart/AD5684
architectures=*
includes=AD5684.h
depends=
