name=FSLP
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for FSLP Force Sensing Linear Potentiometer.
paragraph=
category=Sensors
url=https://github.com/RobTillaart/FSLP
architectures=*
includes=FSLP.h
depends=
