name=GP8403
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for GP8403, I2C 12 bit two channel DAC.
paragraph=
category=Sensors
url=https://github.com/RobTillaart/GP8403
architectures=*
includes=GP8403.h
depends=
