name=M5SWITCH8
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for M5STACK SWITCH8 and BUTTON8 devices.
paragraph=
category=Signal Input/Output
url=https://github.com/RobTillaart/M5SWITCH8
architectures=*
includes=M5SWITCH8.h
depends=
