name=TSW10
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for TSW10 analog turbidity sensor.
paragraph=water,NTU,FTU,FNU,FAU,FBU,FNRU,SEN0189
category=Sensors
url=https://github.com/RobTillaart/TSW10
architectures=*
includes=TSW10.h
depends=
