name=AMC1302
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for AMC1302 current sensor.
paragraph=AMC1300,AMC1301,AMC1311,AMC1351
category=Sensors
url=https://github.com/RobTillaart/AMC1302
architectures=*
includes=AMC1302.h
depends=
