name=A02YYUW
version=0.1.1
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for A02YYUW serial distance sensor
paragraph=IP67,A02YYU,A02YYT,A02YYUT,SEN0311
category=Sensors
url=https://github.com/RobTillaart/A02YYUW
architectures=*
includes=A02YYUW.h
depends=
