name=logicAnalyzer
version=0.1.1
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for building a logicAnalyzer. (non performant).
paragraph=
category=Data Processing
url=https://github.com/RobTillaart/logicAnalyzer
architectures=*
includes=logicAnalyzer.h
depends=
