name=FSR40X
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for FSR40X Force Sensing Resistors.
paragraph=supports FSR400, FSR402, FSR404, FSR406, FSR408
category=Sensors
url=https://github.com/RobTillaart/FSR40X
architectures=*
includes=FSR40X.h
depends=
