name=HC4051
version=0.3.2
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for a HC4051 1x8 channel multiplexer.
paragraph=74HC4051,74HCT4051,CD74HC4051,MC74HC4051A,CD4051BE
category=Sensors
url=https://github.com/RobTillaart/HC4051
architectures=*
includes=HC4051.h
depends=
