name=PT2323
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for PT2323 I2C 6 channel audio processor / selector.
paragraph=
category=Other
url=https://github.com/RobTillaart/PT2323
architectures=*
includes=PT2323.h
depends=
