name=INA226_USI
version=0.6.6
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for INA226 power sensor for ATtiny
paragraph=Voltage Current Volt Ampere
category=Data Processing
url=https://github.com/RobTillaart/INA226_USI
architectures=*
includes=INA226_USI.h
depends=
