name=palindrome
version=0.1.5
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library to do palindrome experiments.
paragraph=
category=Data Processing
url=https://github.com/RobTillaart/palindrome
architectures=*
includes=palindrome.h
depends=
