name=DS3502
version=0.1.1
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for the DS3502, I2C, 7-bit, non-volatile, digital potentiometer.
paragraph=10 kOhm,DS3501,DS3503
category=Sensors
url=https://github.com/RobTillaart/DS3502
architectures=*
includes=DS3502.h
depends=
