name=INA2227
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for the INA2227, I2C, 16 bit, dual channel, voltage, current, power and energy sensor.
paragraph=Voltage current Volt Ampere Joule
category=Data Processing
url=https://github.com/RobTillaart/INA2227
architectures=*
includes=INA2227.h
depends=
