name=TCA6416A_RT
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for TCA6416A I2C 16 bits IO expander.
paragraph=
category=Signal Input/Output
url=https://github.com/RobTillaart/TCA6416A_RT
architectures=*
includes=TCA6416A.h
depends=
