name=US500
version=0.1.1
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for US500 and US4000 underwater distance sensor.
paragraph=temperature
category=Sensors
url=https://github.com/RobTillaart/US500
architectures=*
includes=US500.h
depends=
