name=runTime
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library to measure cumulative series of run times.
paragraph=uptime, runtime, elapsed
category=Sensors
url=https://github.com/RobTillaart/runTime
architectures=*
includes=runTime.h
depends=
