name=DS1682
version=0.1.0
author=Rob Tillaart <rob.tillaart@gmail.com>
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=Arduino library for the I2C DS1682 elapsed time monitor.
paragraph=uptime,runtime
category=Sensors
url=https://github.com/RobTillaart/DS1682
architectures=*
includes=DS1682.h
depends=
